const mongoose = require('../common/connection');
var schema = mongoose.Schema;
var players = new schema({
    // 'enrollmentnumber': String,
    // 'name': String,
    // 'sid': String,
    // 'schemaid': String,
    // // 'universityname': String,
    // 'semester': semObject
});
// var semObject = new schema({
//     'semnumber':SubjectList
// })
// var SubjectList =  new schema({
//     'sebjectid':subject
// });
// var subject =  new schema({
//    'credit':String,
//    'internal':String,
//    'internal1':String,
//    'internal2':String,
//    'internal3':String,
//    'external':String
// });
    // 'pnstitutioncode': Number,
    // 'pnstitutionname': String,
    // 'programmename': String,
    // 'programmecode': String,
    // 'semester1': Object,
    // 'semester2': Object,
    // 'semester3': Object,
    // 'semester4': Object,
    // 'semester5': {
    //     'internal1': String,
    //     'external1': String,
    //     'internal2': String,
    //     'external2': String,
    //     'internal3': String,
    //     'external3': String,
    //     'internal4': String,
    //     'external4': String,
    //     'internal5': String,
    //     'external5': String,
    //     'internal6': String,
    //     'external6': String,
    //     'internal7': String,
    //     'external7': String,
    //     'internal8': String,
    //     'external8': String,
    //     'internal9': String,
    //     'external9': String,
    //     'internal10': String,
    //     'external10': String,
    //     'internal11': String,
    //     'external11': String,
    //     'internal12': String,
    //     'external12': String,
    //     'peparid1': String,
    //     'credit1': String,
    //     'peparid2': String,
    //     'credit2': String,
    //     'peparid3': String,
    //     'credit3': String,
    //     'peparid4': String,
    //     'credit4': String,
    //     'peparid5': String,
    //     'credit5': String,
    //     'peparid6': String,
    //     'credit6': String,
    //     'peparid7': String,
    //     'credit7': String,
    //     'peparid8': String,
    //     'credit8': String,
    //     'peparid9': String,
    //     'credit9': String,
    //     'peparid10': String,
    //     'credit10': String,
    //     'peparid11': String,
    //     'credit11': String,
    //     'peparid12': String,
    //     'credit12': String,
    //     'total1': String,
    //     'grade1': String,
    //     'total2': String,
    //     'grade2': String,
    //     'total3': String,
    //     'grade3': String,
    //     'total4': String,
    //     'grade4': String,
    //     'total5': String,
    //     'grade5': String,
    //     'total6': String,
    //     'grade6': String,
    //     'total7': String,
    //     'grade7': String,
    //     'total8': String,
    //     'grade8': String,
    //     'total9': String,
    //     'grade9': String,
    //     'total10': String,
    //     'grade10': String,
    //     'total11': String,
    //     'grade11': String,
    //     'total12': String,
    //     'grade12': String,
    //     'csremark': String,
    //     'internal1a': Number,
    //     'internal2a': Number,
    //     'internal3a': Number,
    //     'internal4a': Number,
    //     'internal5a': Number,
    //     'internal6a': Number,
    //     'internal7a': Number,
    //     'internal8a': Number,
    //     'internal9a': Number,
    //     'internal10a': Number,
    //     'internal11a': Number,
    //     'internal12a': Number,
    //     'internal1b': Number,
    //     'internal2b': Number,
    //     'internal3b': Number,
    //     'internal4b': Number,
    //     'internal5b': Number,
    //     'internal6b': Number,
    //     'internal7b': Number,
    //     'internal8b': Number,
    //     'internal9b': Number,
    //     'internal10b': Number,
    //     'internal11b': Number,
    //     'internal12b': Number,
    //     'internal1c': Number,
    //     'internal2c': Number,
    //     'internal3c': Number,
    //     'internal4c': Number,
    //     'internal5c': Number,
    //     'internal6c': Number,
    //     'internal7c': Number,
    //     'internal8c': Number,
    //     'internal9c': Number,
    //     'internal10c': Number,
    //     'internal11c': Number,
    //     'internal12c': Number
    // },
    // 'semester6': Object,
    // 'semester7': Object,
    // 'semester8': Object
// });
var PlayerModel = mongoose.model('nplayers', players);
module.exports = PlayerModel;